export const UPDATE_CHECKED_LIST = 'UPDATE_CHECKED_LIST';
export const TOGGLE_CHECK_ALL = 'TOGGLE_CHECK_ALL';
export const TICKET_LOADED = 'TICKET_HEADER_LOADED';
export const ADD_TICKETS = 'ADD_TICKETS';
export const STOP_STATUS = 'STOP_STATUS';
export const CHEAPER_TICKETS = 'CHEAPER_TICKETS';
export const FASTER_TICKETS = 'FASTER_TICKETS';
export const OPTIMAL_TICKETS = 'OPTIMAL_TICKETS';
